### ISSUE TITLE
pasaport integration

### ISSUE THREAD

**Issue by usirin** [kamp-us/monorepo#117]
Integration with pasaport.kamp.us for user & authn/authz operations.

## Tasks
- [ ] create `PASAPORT_URL` environment variable for pano.
- [ ] remix-auth for pasaport
- [ ] login with discord for pasaport
- [ ] #167
