### ISSUE TITLE
Create a documentation site for `@kampus/ui`

### ISSUE THREAD

**Issue by usirin** [kamp-us/monorepo#185]
## Description

We would like to create a documentation website for the @kampus/ui package, our internal react.js component library. This will be a useful resource for our team members to reference and learn how to use the various components in the library.

## Tasks

- [ ] Use a static site generator specifically designed for react.js component libraries, such as [`docz`](https://www.docz.site/) or [`storybook`](https://storybook.js.org), to create the documentation site
- [ ] Add the documentation site to the `apps/ui` folder in the `kamp-us/monorepo` repository
- [ ] Include detailed instructions on how to install and use @kampus/ui in the documentation site
- [ ] Add a search functionality to the documentation site so that users can easily find the information they are looking for
- [ ] Add a section on common problems and solutions to the documentation site, so that users can quickly troubleshoot any issues they may be having with @kampus/ui
- [ ] Publish the documentation site to the URL `https://ui.kamp.us`

## Additional Information

- We suggest using a static site generator specifically designed for react.js component libraries, such as [`docz`](https://www.docz.site/) or [`storybook`](https://storybook.js.org), because they provide built-in support for documenting react.js components and make it easy to create a professional-looking documentation site.
- `docz`:
    - Easy to set up and use
    - Plugin system allows for easy customization and integration with other tools
    - Relatively new and still under active development, so it may have some rough edges and incomplete features
- `storybook`:
    - Focused on building component libraries, so it has a lot of built-in features for documenting react.js components
    - Large ecosystem of plugins and addons allows for easy customization and integration with other tools
    - Can be difficult to set up and configure, especially for complex projects
    - Can be overwhelming to use if we only need a simple documentation site
- Both `docz` and `storybook` have their own unique features and advantages, so it ultimately comes down to which one fits our needs and preferences better.

**Comment by usirin** [comment]
Done with #415
